
[build]
target = "x86_64-blog_os.json"

[unstable] 
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"] # This tells cargo that it should recompile the core and compiler_builtins libraries

[target.'cfg(target_os = "none")']
runner = "bootimage runner"